name: Deploy
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  delete-workflows:
    runs-on: ubuntu-latest
    name: Delete PR workflow runs
    steps:
      - uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        with:
          repository: mxpoliakov/DzygaAnalytics
          event: pull_request
          what-if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
